# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90  
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - dont stale